config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :posts do
    resources :comments
  end

  root "welcome#index"
  get "/auth/github/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout
  resources :users

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	validates :body, presence: true
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :place, presence: true
	validates :time, presence: true
	validates :body, presence: true
	validates :neighborhood, presence: true
	belongs_to :user
	has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :provider, presence: true
	validates :uid, presence: true
	validates :name, presence: true
  has_many :posts
  has_many :comments
  
	def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.nickname = auth["info"]["nickname"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
	after_filter :prepare_unobtrusive_flash

  private
 
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to posts_path
    else
      redirect_to posts_path, :alert => "Comment must contain a message!"
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, except: [:index, :new, :create]
  before_action :require_permission, only: [:destroy]
 
  def index
    @posts = Post.all
    @posts = @posts.order("created_at desc")
    @post = Post.new
  end

  def new
  	@post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.js   {}
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  def require_permission
    if current_user != Post.find(params[:id]).user
      redirect_to posts_path
    end
  end
  
private
  def post_params
    params.require(:post).permit(:time, :body, :place, :neighborhood)
  end

  def find_post
    @post = Post.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create     
		auth = request.env["omniauth.auth"]     
		user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)     
		session[:user_id] = user.id     
		redirect_to posts_path, :notice => "You have successfully signed in!"
  end
 
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "You have successfully signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
	end

	def show
		@user = current_user
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<% if current_page?(root_path) %>
<% else %>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to posts_path, class: "navbar-brand logo-margin" do %>
        <span class="mega-octicon octicon-mark-github"></span> GitGrub
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(posts_path) %>"><%= link_to 'Home', posts_path %></li>
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
      </ul>
      <ul class="nav navbar-nav navbar-right">   
        <% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Logged in as <strong><%= current_user.name %></strong> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'View Profile', user_path(current_user) %></li>
            <li><a href="#">Edit Profile</a></li>
            <li class="divider"></li>
            <li><%= link_to 'Logout', signout_path %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to 'Login', "/auth/github" %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitGrub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<% if current_page?(root_path) %>welcome-bg<% else %>grey-bg<% end %>">

<%= render 'layouts/navbar' %>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<a href="#" class="btn btn-success btn-margin purp"
  data-toggle="modal"
  data-target="#basicModal">Create a post</a>

<div class="modal fade" id="basicModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title" id="myModalLabel">Where are you going to eat?</h4>
      </div>      
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-6 col-md-offset-3 col-padding">
            <%= simple_form_for(@post, remote: true, class: 'form-horizontal') do |f| %>
              <p>
                <%= f.input :place %>
              </p>
              <p>
                <%= f.input :neighborhood %>
              </p>
              <p>
                <%= f.input :time %>
              </p>
              <p>
                <%= f.input :body %>
              </p>
              <p>
                <%= f.button('submit', :class => 'btn btn-success btn-margin purp pull-right', :id => "addSubmit") %>
              </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">  
  $('#addSubmit').click(function() {
    return $('#basicModal').modal('hide');
  });
</script>

app/views/posts/_post.html.erb
<div class="panel panel-default">
  <div class="panel-body">
		<p><strong><%= post.user.name %></strong><br>
			is getting grub at <strong><%= post.place %></strong> around <strong><%= post.time %></strong> in <strong><%= post.neighborhood %></strong>!</p>
			<h4><%= post.body %></h4>

		<hr>

		<div id="comments">
			<% post.comments.each do |comment| %>
			 <div class="well well-sm"><p>
			 			    <strong><em><%= comment.user.name %>:</em></strong><br>
			 			    <%= comment.body %>
			 			  </p></div>

			<% end %>
		</div>

		<div class="container-fluid">
		  <div class="row">
		    <div class="col-md-4">  
		      <%= simple_form_for([post, post.comments.build], class: 'form-horizontal') do |f| %>
		        <p>
		          <%= f.input :body, placeholder: 'Write a comment', label: false, :input_html => {:style => 'width: 300px'} %>
		        </p>
		        <p>
		          <%= f.button 'submit' %>
		        </p>
		      <% end %>
		    </div>
		  </div>
		</div>
  </div>
</div>

app/views/posts/create.js.erb
$("<%= escape_javascript(render @post) %>").prependTo("#posts");

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'edit_form' %>

app/views/posts/index.html.erb
<div class="grey-bg">
	<div class="container" id="main">
	  <div class="row">
	  	<div class="col-md-6 col-md-offset-3">	 
	     	<div class="panel panel-default">
	        
	   			<div class="panel-body">
						<%= render 'form' %>
	      	</div>
	    	</div>

	          <div id="posts">
								<%= render @posts %>
						</div>
	  </div><!--/row-->
	</div>
</div>
 

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.place %></h1>
<p><%= @post.time %></p>
<p><%= @post.neighborhood %></p>
<p><%= @post.body %></p>
<%= link_to 'Edit', edit_post_path(@post) %> | 
<%= link_to 'Delete', @post, method: :delete %>

<br>

<%= form_for @new_comment do |c| %>
	<%= c.hidden_field :post_id, id: 'hidden_post' %>
	<%= c.label :comment_body %>
	<%= c.text_field :comment_body, id: 'comment_body', autofocus: true %>
	<br>
	<%= c.submit 'Save', id: 'ajaxbutton' %>
<% end %>

<br>

<div class="comments">
	<% @post.comments.each do |com| %>	
		<p><%= com.comment_body %></p>
	<% end %>
</div>

app/views/users/new.html.erb
<% if current_user %>
	<% if current_user.name != '' && current_user.name != nil %>
  	<%= "Welcome #{current_user.name}" %>
  <% else %>
  	<%= "Welcome #{current_user.nickname}" %>
  <% end %>
  <%= link_to "Sign out", signout_path %>
<% else %>
  <%= link_to "Sign up with GitHub", "/auth/github" %>
<% end %>

app/views/users/show.html.erb
<div class="grey-bg">
	<div class="container" id="main">
	  <div class="row">
	  	<div class="col-md-6 col-md-offset-3">	 
	     	<div class="panel panel-default">
	   			<div class="panel-body">
						<h2><%= @user.name %></h2>
						<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum neque sapien, scelerisque sit amet luctus tempus, convallis iaculis enim. Cras vulputate ipsum eget ligula pharetra, sed molestie neque ornare. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>
						<%= link_to 'Github', '#' %>
						<h4>Repos:</h4>
						<ul>
							<li>Sample repo name</li>
							<li>Sample repo name</li>
							<li>Sample repo name</li>
							<li>Sample repo name</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/welcome/index.html.erb
	<div class="welcome-container">
    <div class="container">
       <div class="well welcome starter-template">
         <h2>Meet new people</h2>
         <h1>Get lunch with GitGrub</h1>
         <p class="lead">
          <% if current_user %>
  					<h2><%= link_to 'Enter', posts_path, class: 'btn btn-success btn-margin purp' %></h2>
            <p><%= link_to 'Sign out', signout_path, :class => 'purple' %></p>
  				<% else %>
    				<h3><%= link_to("/auth/github", class: 'purple') do %>Sign up with Github <span class="mega-octicon octicon-mark-github"></span><% end %></h3>
  				<% end %>
  			</p>
      </div>
    </div><!-- /.container -->
  </div>